"""Add EquipeInteracao table for team interactions

Revision ID: 7254c34a3657
Revises: f3d381a19c7b
Create Date: 2025-09-04 22:24:21.405962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7254c34a3657'
down_revision = 'f3d381a19c7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe_interacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_funcionario', sa.String(), nullable=False),
    sa.Column('resposta_gerada', sa.String(), nullable=False),
    sa.Column('parametros_rag', sa.JSON(), nullable=True),
    sa.Column('fontes_kb', sa.JSON(), nullable=True),
    sa.Column('resultado_simulacao', sa.JSON(), nullable=True),
    sa.Column('funcionario_id', sa.String(), nullable=True),
    sa.Column('sessao_id', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipe_interacao')
    # ### end Alembic commands ###
