"""Adicionar modelos ContextoLead e FilaRevisao

Revision ID: 9962c7a8cc6e
Revises: 0001_init
Create Date: 2025-09-01 15:07:22.830746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9962c7a8cc6e'
down_revision = '0001_init'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexto_lead',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('procedimento_ativo', sa.String(), nullable=True),
    sa.Column('etapa_ativa', sa.String(), nullable=True),
    sa.Column('aguardando', sa.JSON(), nullable=True),
    sa.Column('ultima_automacao_enviada', sa.String(), nullable=True),
    sa.Column('ultimo_topico_kb', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('fila_revisao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(), nullable=False),
    sa.Column('resposta', sa.String(), nullable=False),
    sa.Column('fontes_kb', sa.JSON(), nullable=True),
    sa.Column('automacao_equivalente', sa.String(), nullable=True),
    sa.Column('pontuacao_similaridade', sa.Float(), nullable=True),
    sa.Column('contexto_do_lead', sa.JSON(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fila_revisao_lead_id'), 'fila_revisao', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fila_revisao_lead_id'), table_name='fila_revisao')
    op.drop_table('fila_revisao')
    op.drop_table('contexto_lead')
    # ### end Alembic commands ###
