"""Add timeline_expects_reply column to contexto_lead

Revision ID: f3d381a19c7b
Revises: 9962c7a8cc6e
Create Date: 2025-09-03 01:34:25.417886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d381a19c7b'
down_revision = '9962c7a8cc6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contexto_lead', sa.Column('timeline_expects_reply', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contexto_lead', 'timeline_expects_reply')
    # ### end Alembic commands ###
